[project]
name = "dev-agents-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk===2.11.0",
]

[project.scripts]
dev-agents-ia = "dev_agents_ia:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
